### ISSUE TITLE
SyntaxError: invalid syntax. Can not import the package

### ISSUE THREAD

**Issue by andy-yangz** [williamFalcon/test-tube#2]
I installed this package in my py2.7 environment, but after I import it I got this error.
I don't know how to fix it, beacause it seems all the code is right.
```
import test_tube
│Traceback (most recent call last):
│  File "<stdin>", line 1, in <module>
│  File "/home/andy/.conda/envs/dynet/lib/python2.7/site-packages/test_tube/__init__.py", line 5, in <module>
│    from .argparse_hopt import HyperOptArgumentParser
│  File "/home/andy/.conda/envs/dynet/lib/python2.7/site-packages/test_tube/argparse_hopt.py", line 38
│    def add_opt_argument_list(self, *args, options=None, tunnable=False, **kwargs):
│    
│SyntaxError: invalid syntax
```

**Comment by williamFalcon** [comment]
ummmm.  which version of test_tube?  is it only happening on python 2.7?
