### ISSUE TITLE
Permission denied when running examples possibly because os.makedirs()

### ISSUE THREAD

**Issue by yuqli** [williamFalcon/test-tube#41]
When I try to run the example `/tensorflow_example.py"` from a conda environment, I got the "permission denied" error. It seems the script is trying to write to the `/Users` folder - I'm not sure why that's not allowed. 

When I try running Python with `sudo`, there is another issue that `sudo` changes $PATH and I'm using a different python, which does not have tensorflow installed.[ This answer ](https://stackoverflow.com/questions/30626160/anaconda-python-not-available-from-sudo)also suggests not running python in sudo mode...

So I guess the real question is how to make `os.mkdirs()` work on my system (Ubuntu 16.04). Found an answer [here](https://stackoverflow.com/questions/5231901/permission-problems-when-creating-a-dir-with-os-makedirs-in-python). While I'm looking into the `os.mkdirs()` permission issue, just think I could open an issue in case other users come into the same situation as well.
 
Here is the full error log:

```
(deep) yuqiong@yuqiong-G7-7588:/media/yuqiong/DATA/test-tube$ python examples/tensorflow_example.py
Caught exception in worker thread [Errno 13] Permission denied: '/Users'
Caught exception in worker thread [Errno 13] Permission denied: '/Users'
Caught exception in worker thread [Errno 13] Permission denied: '/Users'
Caught exception in worker thread [Errno 13] Permission denied: '/Users'
Traceback (most recent call last):
Traceback (most recent call last):
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/site-packages/test_tube/argparse_hopt.py", line 29, in optimize_parallel_gpu_private
    results = train_function(trial_params)
  File "examples/tensorflow_example.py", line 20, in train
    autosave=False,
Traceback (most recent call last):
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/site-packages/test_tube/log.py", line 58, in __init__
    self.__init_cache_file_if_needed()
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/site-packages/test_tube/log.py", line 121, in __init_cache_file_if_needed
    os.makedirs(exp_cache_file)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/site-packages/test_tube/argparse_hopt.py", line 29, in optimize_parallel_gpu_private
    results = train_function(trial_params)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/site-packages/test_tube/argparse_hopt.py", line 29, in optimize_parallel_gpu_private
    results = train_function(trial_params)
  File "examples/tensorflow_example.py", line 20, in train
    autosave=False,
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/site-packages/test_tube/log.py", line 58, in __init__
    self.__init_cache_file_if_needed()
  File "examples/tensorflow_example.py", line 20, in train
    autosave=False,
PermissionError: [Errno 13] Permission denied: '/Users'
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/site-packages/test_tube/log.py", line 121, in __init_cache_file_if_needed
    os.makedirs(exp_cache_file)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/site-packages/test_tube/log.py", line 58, in __init__
    self.__init_cache_file_if_needed()
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/site-packages/test_tube/log.py", line 121, in __init_cache_file_if_needed
    os.makedirs(exp_cache_file)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
  [Previous line repeated 2 more times]
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users'
PermissionError: [Errno 13] Permission denied: '/Users'
Traceback (most recent call last):
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/site-packages/test_tube/argparse_hopt.py", line 29, in optimize_parallel_gpu_private
    results = train_function(trial_params)
  File "examples/tensorflow_example.py", line 20, in train
    autosave=False,
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/site-packages/test_tube/log.py", line 58, in __init__
    self.__init_cache_file_if_needed()
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/site-packages/test_tube/log.py", line 121, in __init_cache_file_if_needed
    os.makedirs(exp_cache_file)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  [Previous line repeated 2 more times]
  File "/media/yuqiong/DATA/Anaconda3/envs/deep/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users'

```

**Comment by yuqli** [comment]
I figured out why. It's with the `log_path` argument in the `tensorflow_example.py` file, where `log_path` is set to `/Users/waf/Desktop/test`. I do not have this path on my machine, and that's causing the problem.

And in `log.py`, it is specified that if there is an input to `log_path` it will use that path, or else it will save log to the directory where the `test-tube` module is installed.
